export const apiKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWIyODg3NDA4Mjk2MzAwMTgwMWVlOGEiLCJpYXQiOjE3MDYxOTkxNTYsImV4cCI6MTcwNzQwODc1Nn0.CyDeEiJlPv7HLEb4KvtRws2nbjEYJFHlnXB5_MkbkRs'
export const usersListUrl = 'https://striveschool-api.herokuapp.com/api/profile/'
export const userProfileUrl = 'https://striveschool-api.herokuapp.com/api/profile/me'
export const experiencesListUrl = 'https://striveschool-api.herokuapp.com/api/profile/'
export const postListUrl = 'https://striveschool-api.herokuapp.com/api/posts/'
